nodes:
  master:
    box: centos/stream9
    provider:
      kind: libvirt
      cpus: 2
      memory: 2048
    provisioners:
      - kind: shell
        inline: |
          sudo swapoff -a
          sudo sed -i -r '/^[^#].+\s+swap\s+/ s/^/# /' /etc/fstab
      - kind: shell
        inline: |
          echo 'export PATH="/usr/local/bin:$PATH"' | tee /etc/profile.d/local-bin.sh
          chmod +x /etc/profile.d/local-bin.sh
      - kind: k3s
